### ISSUE TITLE
Reset only resets Yaw

### ISSUE THREAD

**Issue by cartycrabber** [kauailabs/navxmxp#45]
The Reset function (at least in Java and C++) only resets the gyro Z axis. Is there any reason it does not reset all three axes? Our RoboRio is mounted sideways this year, meaning we are using a different axis as our "yaw", but there is no easy way to reset it.

**Comment by jrjparks** [comment]
Use the built in [OmniMount](http://www.pdocs.kauailabs.com/navx-mxp/installation/omnimount/) to set the NavX's orientation.

**Comment by kauailabs** [comment]
Closed.  This issue is addressed via the Omnimount feature.
