### ISSUE TITLE
AHRS should implement the Gyro Interface

### ISSUE THREAD

**Issue by SagarPatel201** [kauailabs/navxmxp#68]
The AHRS class already implements most of the Gyro interface's methods, so it would make sense to also implement Gyro alongside PIDSource and Sendable. This would allow us to be able to easily swap the NavX in and out with other gyros that implement the Gyro interface.

**Comment by gartaud** [comment]
I agree!

**Comment by kauailabs** [comment]
Implemented and released in v. 3.1.405.
