### ISSUE TITLE
Java samples does not work

### ISSUE THREAD

**Issue by ThadHouse** [kauailabs/navxmxp#8]
Currently, myRobot is only constructed with 2 motors in the samples. However, mecanumDrive_Catesian requires a 4 motor drive, and throws a null pointer exception when attempted to be used with a 2 motor drive. Since all exceptions are caught, this doesn't throw, however it doesn't work properly either. It will only set the front left motor before throwing and not continuing.

**Comment by kauailabs** [comment]
Thanks @ThadHouse; the master branch (and the latest build.zip file) has had several of the Java examples updated to use the 4-parameter constructor to the RobotDrive class.
