### ISSUE TITLE
NavX does not report using FRC's usage reporting

### ISSUE THREAD

**Issue by sciencewhiz** [kauailabs/navxmxp#82]
In the[ usage reporting spreadsheet from 2019](https://www.firstinspires.org/robotics/frc/blog/2020-beta-testing-usage-report), the NavX is not reported.

**Comment by kauailabs** [comment]
@sciencewhiz, I've added usage reporting for C++, Java (now available on the navX software download page, as version 3.1.390).

Do you know how one can add Usage Reporting from LabVIEW?  I couldn't figure that part out....

**Comment by sciencewhiz** [comment]
You can use this VI Snippet for usage reporting in LabVIEW. 
![NavXUsageReporting](https://user-images.githubusercontent.com/4885091/68999870-b6420100-087b-11ea-9549-b37472afa5b3.png)

**Comment by kauailabs** [comment]
@sciencewhiz, we just release 3.1.400 of the navX-MXP RoboRIO software; this includes updated LabVIEW VIs which use the code snippet you've provided to update the usage reporting.  Thanks for the help!
