### ISSUE TITLE
NavX examples don't compile with 2020 wpilib

### ISSUE THREAD

**Issue by sciencewhiz** [kauailabs/navxmxp#85]
2020's wpilib removes SampleRobot, which means that the NavX examples don't compile. In addition, the examples are still eclipse projects, and not VS Code / gradle projects.

**Comment by kauailabs** [comment]
@sciencewhiz, the updated C++ and Java examples (which are now in a "vscode" subdirectory underneath the corresponding examples directories) are now available on the navX software download page, as version 3.1.390.  They inherit now from TimedRobot, not SampleRobot - and are converted to VSCode projects.

I haven't yet verified compilation on 2020 wpilib, but believe that should also work - after the build.gradle is changed to the new wpilib build.  Once the final release for 2020 season is ready, I plan update the build.gradle files in the examples.  Let me know if you run into any troubles.
