### ISSUE TITLE
Please remove `using namespace frc` in AHRS.h

### ISSUE THREAD

**Issue by Lytigas** [kauailabs/navxmxp#89]
This pollutes the global namespace of any source that includes the header, and could trick unwitting programmers into not writing `frc::` only to be dumbfounded once  removing `#include "AHRS.h"` breaks all their symbols. Not having using declarations in headers is a well-documented best practice: https://stackoverflow.com/a/5849668

**Comment by kauailabs** [comment]
Thanks for catching this, it's now fixed.  You can acquire it by updating to the latest online vendor deps URL (https://www.kauailabs.com/dist/frc/2020/navx_frc.json).  The latest version of the libraries with this change is 3.1.403.
