### ISSUE TITLE
When trying to instantiate AHRS class in latest update, compilation fails

### ISSUE THREAD

**Issue by r4stered** [kauailabs/navxmxp#92]
When compiling code using the latest release of the library, compilation fails. Here is the error log:

https://pastebin.com/raw/2tCRsZAr

In the FRC Discord, @calcmogul and I were talking and it seems that the const-ness of those function is incorrect.

'> They got the constness of those functions wrong so it didn't override the pure virtual functions. Using override would have caught this and thrown a compiler error during library build.
@calcmogul#3301 '

**Comment by kauailabs** [comment]
Thanks for catching this; the diagnosis re: constness was exactly correct - the override keyword was added to the overridden Gyro interface methods in AHRS.h to help the compiler catch it.  It's resolved in v. 3.1.409.  Update your vendordeps if using online installation, or download and run the latest installer to get that.
