### ISSUE TITLE
Java Docs index.html incomplete, missing AHRS for example

### ISSUE THREAD

**Issue by brettle** [kauailabs/navxmxp#97]
This link does not include critical classes like `AHRS`:

https://www.kauailabs.com/public_files/navx-mxp/apidocs/java/index.html

even though they are online under that same path:

https://www.kauailabs.com/public_files/navx-mxp/apidocs/java/com/kauailabs/navx/frc/AHRS.html

Not sure if that's an issue with this repo or not.

**Comment by kauailabs** [comment]
Thanks, the link now points to the AHRS class documentation.
