### ISSUE TITLE
Docs example for java simulation does not work

### ISSUE THREAD

**Issue by 28andrew** [kauailabs/navxmxp#98]
In the library docs for [Java](https://pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/), the provided code snippet:
```java
int dev = SimDeviceDataJNI.getSimDeviceHandle(“navX-Sensor”);
SimDouble angle = new SimDouble(SimDeviceDataJNI.getSimValueHandle(dev, “Yaw”));
angle.set(5.0);
```
does not work. `navX-Sensor` should be replaced with `navX-Sensor[0]` as [this](https://github.com/kauailabs/navxmxp/blob/master/roborio/java/navx_frc/src/com/kauailabs/navx/frc/AHRS.java#L1031) is how the SimDevice is created in the library. I would guess the C++ example has the same issue.

**Comment by kauailabs** [comment]
Fixed on the website; thanks for reporting this!
